name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'
      
      # ADD THIS DEBUG STEP TO SEE THE FILES IN THE RUNNER
      - name: List all files in runner
        run: ls -la

      - name: Run Go Releaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          distribution: goreleaser
          args: release --clean --debug --skip-validate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}